[package]
name = "string_studio"
description = "Random string generator for faster and consistant naming when writing content."
license = "MIT"
readme = "README.md"
version = "0.1.0"
authors = ["Zachary Frost"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
